Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DATABASE_URL: !Ref DATABASEURL

Parameters:
  DATABASEURL:
    Type: String
    Default: mongodb://mongo:27017/credit-db
    Description: database url

Resources:
  CheckCredit:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Timeout: 180
      Handler: src/index.handler
      Events:
        CheckCreditAPI:
          Type: Api
          Properties:
            Path: /check-credit
            Method: post
