Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        DATABASE_URL: "mongodb://prod/credit-db"
Resources:
  CheckCredit:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Timeout: 180
      Handler: src/index.handler
      Events:
        CheckCreditAPI:
          Type: Api
          Properties:
            Path: /check-credit
            Method: post